[package]
name = "polkadot-rpc"
version = "0.8.26"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.1.0"
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-blockchain = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-keystore = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-api = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-consensus = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sp-consensus-babe = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
sc-chain-spec = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
sc-rpc = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
sc-consensus-babe = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"}
sc-consensus-babe-rpc = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"}
sc-consensus-epochs = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"}
sc-finality-grandpa = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
sc-finality-grandpa-rpc = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
sc-keystore = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"}
sc-sync-state-rpc = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"}
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing"  }
pallet-transaction-payment-rpc = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-block-builder = { git = "https://github.com/mxinden/substrate", branch = "auth-disc-timing" }
